/// Validation tests comparing molprint fingerprints against RDKit reference data.
///
/// Reference data is generated by `scripts/generate_reference.py` (requires RDKit).
/// ChEMBL corpus reference is generated by `scripts/corpus_validate.py`.
/// Tests skip gracefully when reference files are absent.
///
/// MACCS: bit-exact comparison against RDKit's GetMACCSKeysFingerprint.
/// Morgan: Pearson correlation of pairwise Tanimoto similarities.
use molprint_core::smiles::parse_smiles;
use molprint_fp::maccs::Maccs166;
use molprint_fp::morgan::Morgan;
use molprint_fp::traits::Fingerprinter;
use molprint_search::metrics::tanimoto;
use std::collections::HashMap;
use std::path::Path;

fn reference_path(filename: &str) -> std::path::PathBuf {
    // Tests run from the crate root; reference files are at workspace root/scripts/
    let manifest = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest.join("../../scripts").join(filename)
}

fn skip_if_missing(path: &Path) -> bool {
    if !path.exists() {
        eprintln!(
            "SKIP: reference file {} not found.\n\
             Run `python scripts/generate_reference.py` first.",
            path.display()
        );
        return true;
    }
    false
}

// ── MACCS validation ─────────────────────────────────────────────────────────

#[test]
fn validate_maccs_against_rdkit() {
    let path = reference_path("reference_maccs.tsv");
    if skip_if_missing(&path) {
        return;
    }

    let content = std::fs::read_to_string(&path).expect("read reference_maccs.tsv");
    let fp_algo = Maccs166::new();

    let mut total = 0usize;
    let mut wrong_molecules = 0usize;
    // bit_errors[bit] = (false_positives, false_negatives)
    let mut bit_errors: HashMap<usize, (usize, usize)> = HashMap::new();

    for line in content.lines().skip(1) {
        // skip header
        let parts: Vec<&str> = line.splitn(3, '\t').collect();
        if parts.len() < 3 {
            continue;
        }
        let (smiles, name, bits_str) = (parts[0], parts[1], parts[2]);

        let mol = match parse_smiles(smiles) {
            Ok(m) => m,
            Err(e) => {
                eprintln!("SKIP {name}: parse error: {e}");
                continue;
            }
        };

        // RDKit reference: set of bit indices (1-indexed, bit 0 always 0)
        let rdkit_bits: std::collections::HashSet<usize> = bits_str
            .split(',')
            .filter(|s| !s.is_empty())
            .filter_map(|s| s.parse::<usize>().ok())
            .collect();

        // molprint: bits 0-165 where bit N = MACCS key N
        let fp = fp_algo.fingerprint(&mol);
        let molprint_bits: std::collections::HashSet<usize> =
            (0..166).filter(|&i| fp.get(i)).collect();

        // Compare bits 1-165 (bit 166 not representable in our 166-bit fp)
        let rdkit_cmp: std::collections::HashSet<usize> =
            rdkit_bits.iter().copied().filter(|&b| b <= 165).collect();

        if rdkit_cmp != molprint_bits {
            wrong_molecules += 1;
            let false_pos: Vec<usize> = molprint_bits.difference(&rdkit_cmp).copied().collect();
            let false_neg: Vec<usize> = rdkit_cmp.difference(&molprint_bits).copied().collect();
            eprintln!("MISMATCH {name} ({smiles}):");
            if !false_pos.is_empty() {
                let mut fp_sorted = false_pos.clone();
                fp_sorted.sort();
                eprintln!("  false positives (molprint set, RDKit unset): {fp_sorted:?}");
                for b in false_pos {
                    bit_errors.entry(b).or_default().0 += 1;
                }
            }
            if !false_neg.is_empty() {
                let mut fn_sorted = false_neg.clone();
                fn_sorted.sort();
                eprintln!("  false negatives (RDKit set, molprint unset): {fn_sorted:?}");
                for b in false_neg {
                    bit_errors.entry(b).or_default().1 += 1;
                }
            }
        }
        total += 1;
    }

    if !bit_errors.is_empty() {
        let mut sorted: Vec<_> = bit_errors.iter().collect();
        sorted.sort_by_key(|(&k, _)| k);
        eprintln!("\nPer-bit error summary (bit: fp/fn across all molecules):");
        for (bit, (fp, fn_)) in &sorted {
            eprintln!("  key {bit:3}: {fp} false-pos, {fn_} false-neg");
        }
    }

    let correct = total - wrong_molecules;
    eprintln!(
        "\nMACS validation: {correct}/{total} molecules fully correct ({:.1}%)",
        100.0 * correct as f64 / total as f64
    );

    assert_eq!(
        wrong_molecules, 0,
        "{wrong_molecules}/{total} molecules had MACCS bit mismatches vs RDKit (see stderr)"
    );
}

// ── ChEMBL corpus MACCS accuracy ─────────────────────────────────────────────

/// Large-scale validation against a 10k ChEMBL sample.
///
/// Reference file `scripts/chembl_10k_maccs.tsv` is generated by
/// `scripts/corpus_validate.py` after running `scripts/download_chembl_sample.py`.
///
/// Format (tab-separated, with header):
///     smiles  id  rdkit_bits
/// where `rdkit_bits` is a comma-separated list of RDKit MACCS bit indices (1-indexed).
#[test]
fn validate_maccs_against_chembl_corpus() {
    let path = reference_path("chembl_10k_maccs.tsv");
    if skip_if_missing(&path) {
        return;
    }

    let content = std::fs::read_to_string(&path).expect("read chembl_10k_maccs.tsv");
    let fp_algo = Maccs166::new();
    const TARGET_ACCURACY: f64 = 99.0;

    let mut total = 0usize;
    let mut mismatches = 0usize;

    for line in content.lines().skip(1) {
        let parts: Vec<&str> = line.splitn(3, '\t').collect();
        if parts.len() < 3 {
            continue;
        }
        let (smiles, name, bits_str) = (parts[0], parts[1], parts[2]);

        let mol = match parse_smiles(smiles) {
            Ok(m) => m,
            Err(e) => {
                eprintln!("SKIP {name}: parse error: {e}");
                continue;
            }
        };

        let rdkit_bits: std::collections::HashSet<usize> = bits_str
            .split(',')
            .filter(|s| !s.is_empty())
            .filter_map(|s| s.trim().parse::<usize>().ok())
            .filter(|&b| b >= 1 && b <= 165)
            .collect();

        let fp = fp_algo.fingerprint(&mol);
        let molprint_bits: std::collections::HashSet<usize> =
            (1..=165).filter(|&i| fp.get(i)).collect();

        if rdkit_bits != molprint_bits {
            mismatches += 1;
        }
        total += 1;
    }

    if total == 0 {
        eprintln!("SKIP: no molecules in corpus file");
        return;
    }

    let correct = total - mismatches;
    let accuracy = 100.0 * correct as f64 / total as f64;
    eprintln!("\nChEMBL corpus MACCS: {correct}/{total} exact matches ({accuracy:.2}%)");

    assert!(
        accuracy >= TARGET_ACCURACY,
        "ChEMBL corpus MACCS accuracy {accuracy:.2}% < {TARGET_ACCURACY}% \
         ({mismatches}/{total} mismatches)"
    );
}

// ── Morgan Tanimoto correlation ───────────────────────────────────────────────

#[test]
fn validate_morgan_tanimoto_correlation() {
    let path = reference_path("reference_morgan_sims.tsv");
    if skip_if_missing(&path) {
        return;
    }

    let content = std::fs::read_to_string(&path).expect("read reference_morgan_sims.tsv");
    let algo = Morgan::new(2, 2048);

    // Cache parsed molecules
    let mut mol_cache: HashMap<String, _> = HashMap::new();

    let mut rdkit_sims = Vec::new();
    let mut molprint_sims = Vec::new();
    let mut skipped = 0usize;

    for line in content.lines().skip(1) {
        let parts: Vec<&str> = line.splitn(5, '\t').collect();
        if parts.len() < 5 {
            continue;
        }
        let (sa, sb, rdkit_sim_str) = (parts[2], parts[3], parts[4]);
        let rdkit_sim: f64 = match rdkit_sim_str.parse() {
            Ok(v) => v,
            Err(_) => continue,
        };

        let mol_a = mol_cache
            .entry(sa.to_string())
            .or_insert_with(|| parse_smiles(sa).ok());
        let mol_a = match mol_a.as_ref() {
            Some(m) => m.clone(),
            None => {
                skipped += 1;
                continue;
            }
        };
        let mol_b = mol_cache
            .entry(sb.to_string())
            .or_insert_with(|| parse_smiles(sb).ok());
        let mol_b = match mol_b.as_ref() {
            Some(m) => m.clone(),
            None => {
                skipped += 1;
                continue;
            }
        };

        let fp_a = algo.fingerprint(&mol_a);
        let fp_b = algo.fingerprint(&mol_b);
        let mp_sim = tanimoto(&fp_a, &fp_b);

        rdkit_sims.push(rdkit_sim);
        molprint_sims.push(mp_sim);
    }

    let n = rdkit_sims.len() as f64;
    assert!(n > 10.0, "too few pairs to correlate: {n}");

    // Pearson correlation
    let mean_r: f64 = rdkit_sims.iter().sum::<f64>() / n;
    let mean_m: f64 = molprint_sims.iter().sum::<f64>() / n;
    let cov: f64 = rdkit_sims
        .iter()
        .zip(molprint_sims.iter())
        .map(|(r, m)| (r - mean_r) * (m - mean_m))
        .sum::<f64>();
    let std_r: f64 = rdkit_sims
        .iter()
        .map(|r| (r - mean_r).powi(2))
        .sum::<f64>()
        .sqrt();
    let std_m: f64 = molprint_sims
        .iter()
        .map(|m| (m - mean_m).powi(2))
        .sum::<f64>()
        .sqrt();

    let pearson = if std_r * std_m > 0.0 {
        cov / (std_r * std_m)
    } else {
        1.0
    };

    // Mean absolute error
    let mae: f64 = rdkit_sims
        .iter()
        .zip(molprint_sims.iter())
        .map(|(r, m)| (r - m).abs())
        .sum::<f64>()
        / n;

    eprintln!(
        "\nMorgan Tanimoto correlation ({} pairs, {skipped} skipped):",
        rdkit_sims.len()
    );
    eprintln!("  Pearson r = {pearson:.4}");
    eprintln!("  MAE       = {mae:.4}");

    assert!(
        pearson >= 0.90,
        "Morgan Tanimoto Pearson r={pearson:.4} < 0.90 vs RDKit"
    );
    assert!(mae <= 0.10, "Morgan Tanimoto MAE={mae:.4} > 0.10 vs RDKit");
}
